baseURL: 'https://risotto.joeroe.io'
theme: risotto
title: risotto demo
author: Joe Roe
copyright: Â© [Joe Roe](https://joeroe.io) & [risotto contributors](https://github.com/joeroe/risotto/graphs/contributors).
paginate: 3
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors:
  - error-remote-getjson

# Automatically add content sections to main menu
sectionPagesMenu: main
params:
  noindex: false
  theme:
    palette: base16-dark

# Sidebar: about/bio
  about:
    title: risotto
    description: 'A [hugo](https://gohugo.io) theme inspired by terminal ricing.'
    logo: images/rice.svg

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

  socialLinks:
    - icon: fa-brands fa-github
      title: GitHub
      url: 'https://github.com/joeroe/risotto'
    - icon: fa-solid fa-envelope
      title: Email
      url: 'mailto:example@example.com'
    - icon: ai ai-orcid
      title: ORCID
      url: 'https://orcid.org/0000-0001-2345-6789'
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
taxonomies:
  category: categories
  tag: tags
  series: series

# For hugo >= 0.60.0, enable inline HTML
markup:
  goldmark:
    renderer:
      unsafe: true
  # Table of contents
  # Add toc = true to content front matter to enable
  tableOfContents:
    startLevel: 2
    endLevel: 3
    ordered: true
privacy:
  vimeo:
    disabled: false
    simple: true
  twitter:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true
services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true